const products = [{
        id: 1,
        title: 'Large Cyclops',
        name: 'Head-big-eye',
        description: "A robot head with an unusually large eye and teloscpic neck -- excellent for exploring high spaces.",
        image: require('../assets/head-big-eye.png'),
        type: 'Heads',
        cost: 200,
    },
    {
        id: 2,
        title: 'Friendly',
        name: 'Head-friendly',
        description: "A friendly robot head with two eyes and a smile -- great for domestic use.",
        image: require('../assets/head-friendly.png'),
        type: 'Heads',
        cost: 150,
    },
    {
        id: 3,
        title: 'Shredder',
        name: 'Head-shredder',
        description: "A large three-eyed head with a shredder for a mouth -- great for crushing light medals or shredding documents.",
        image: require('../assets/head-shredder.png'),
        type: 'Heads',
        cost: 300,
    },
    {
        id: 4,
        title: 'Small Cyclops',
        name: 'Head-single-eye',
        description: "A simple single-eyed head -- simple and inexpensive.",
        image: require('../assets/head-single-eye.png'),
        type: 'Heads',
        cost: 500,
    },
    {
        id: 5,
        title: 'Surveillance',
        name: 'Head-surveillance',
        description: "A robot head with three oscillating eyes -- excellent for surveillance.",
        image: require('../assets/head-surveillance.png'),
        type: 'Heads',
        cost: 100,
    },
    {
        id: 6,
        title: 'Articulated',
        name: 'Arm-articulated',
        description: "An articulated arm with a claw -- great for reaching around corners or working in tight spaces.",
        image: require('../assets/arm-articulated-claw.png'),
        type: 'Arms',
        cost: 350,
    },
    {
        id: 7,
        title: 'Two Clawed',
        name: 'Arm-dual-claw',
        description: "An arm with two independent claws -- great when you need an extra hand. Need four hands? Equip your bot with two of these arms.",
        image: require('../assets/arm-dual-claw.png'),
        type: 'Arms',
        cost: 800,
    },
    {
        id: 8,
        title: 'Grabber',
        name: 'Arm-grabber',
        description: "A telescoping arm with a grabber.",
        image: require('../assets/arm-grabber.png'),
        type: 'Arms',
        cost: 350,
    },
    {
        id: 9,
        title: 'Propeller',
        name: 'Arm-propeller',
        description: "An arm with a propeller -- good for propulsion or as a cooling fan.",
        image: require('../assets/arm-propeller.png'),
        type: 'Arms',
        cost: 550,
    },
    {
        id: 10,
        title: 'Stubby Claw',
        name: 'Arm-stubby-claw',
        description: "A short and stubby arm with a claw -- simple, but cheap.",
        image: require('../assets/arm-stubby-claw.png'),
        type: 'Arms',
        cost: 600,
    },
    {
        id: 11,
        title: 'Flexible gauged',
        name: 'Torso-flexible-gauged',
        description: "A torso that can bend slightly at the waist and equiped with a heat guage.",
        image: require('../assets/torso-flexible-gauged.png'),
        type: 'Torsos',
        cost: 250,
    },
    {
        id: 12,
        title: 'Gauged',
        name: 'Torso-gauged',
        description: "A less flexible torso with a battery gauge.",
        image: require('../assets/torso-gauged.png'),
        type: 'Torsos',
        cost: 100,
    },
    {
        id: 13,
        title: 'Pouch V1',
        name: 'Torso-pouch',
        description: "A simple torso with a pouch for carrying items.",
        image: require('../assets/torso-pouch.png'),
        type: 'Torsos',
        cost: 550,
    },
    {
        id: 14,
        title: 'Pouch V2',
        name: 'Torso-pouch',
        description: "A better torso with a pouch for carrying items.",
        image: require('../assets/torso-pouch.png'),
        type: 'Torsos',
        cost: 750,
    },
    {
        id: 15,
        title: 'Pouch V3',
        name: 'Torso-pouch',
        description: "The best torso with a pouch for carrying items.",
        image: require('../assets/torso-pouch.png'),
        type: 'Torsos',
        cost: 950,
    },
    {
        id: 16,
        title: 'Double Wheeled',
        name: 'Base-double-wheel',
        description: "A two wheeled base with an accelerometer for stability.",
        image: require('../assets/base-double-wheel.png'),
        type: 'Bases',
        cost: 750,
    },
    {
        id: 17,
        title: 'Rocket',
        name: 'Base-rocket',
        description: "A rocket base capable of high speed, controlled flight.",
        image: require('../assets/base-rocket.png'),
        type: 'Bases',
        cost: 900,
    },
    {
        id: 18,
        title: 'Single Wheeled',
        name: 'Base-single-wheel',
        description: "A single-wheeled base with an accelerometer capable of higher speeds and navigating rougher terrain than the two-wheeled variety.",
        image: require('../assets/base-single-wheel.png'),
        type: 'Bases',
        cost: 750,
    },
    {
        id: 19,
        title: 'Spring',
        name: 'Base-spring',
        description: "A spring base - great for reaching high places.",
        image: require('../assets/base-spring.png'),
        type: 'Bases',
        cost: 350,
    },
    {
        id: 20,
        title: 'Triple Wheeled',
        name: 'Base-triple-wheel',
        description: "An inexpensive three-wheeled base. only capable of slow speeds and can only function on smooth surfaces.",
        image: require('../assets/base-triple-wheel.png'),
        type: 'Bases',
        cost: 200,
    },
]

export default products;